defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

baseurl: ""
url: "http://amokjs.com"
analytics: UA-48351156-5

highlight: pygments

kramdown:
  input: GFM
  hard_wrap: false

embedly:
  api_key: 4a6f19a3b7144d68bb3ef2c823d42ef5

gems:
  - jekyll-sitemap
