baseurl: ""
analytics: UA-48351156-5
embedly: 4a6f19a3b7144d68bb3ef2c823d42ef5

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

markdown:       kramdown
highlighter:    pygments
kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-sitemap
