baseurl: ""
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

markdown:       kramdown
highlighter:    pygments
kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-sitemap
