# Site settings
title: Amok
description: Live Editing for JavaScript Without Having to Reload

baseurl: ""
url: "http://amokjs.com"

npm: https://www.npmjs.com/package/amok
github: https://github.com/caspervonb/amok
gitter: https://gitter.im/caspervonb/amok

analytics: UA-48351156-5

gems:
  - jekyll-sitemap
